version: '3.7'

services:
  nsav-api:
    container_name: nsav-api
    build:
      context: .
      dockerfile: ./compose/local/backend/Dockerfile
    command: /start.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8001:8000
    env_file:
      - .env/.dev
    depends_on:
      - nsav-db

  nsav-db:
    container_name: nsav-db
    image: edgedb/edgedb
    volumes:
      - ./backend/dbschema:/dbschema
      - edgedb-data:/var/lib/edgedb/data
    expose:
      - 5656
    environment:
      - EDGEDB_USER=edgedb
      - EDGEDB_PASSWORD=edgedb

  tacacs:
    container_name: tacacs
    image: lfkeitel/tacacs_plus:alpine
    expose:
      - 49
volumes:
  edgedb-data: